# Week 1 Asynchronous

Getting Started with Data Visualization in R > Week 1

- [Base R cheat sheet](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf)

```{r, include = FALSE}
source("_common.R")
```

## Installing R and Getting Started

```{r include=FALSE}
# knitr::spin("week1/1w1_1.R")
# {r child = 'week1/1w1_1.R'}
```

## R basics

### Basic R
```{r, code = readLines("week1/1w1_1.R")}

```

### Functions in R

```{r, code = readLines("week1/1w1_2.R")}

```

## Dataframe
```{r, code = readLines("week1/1w1_3.R")}

```

## Basics of Importing Data into R
```{r, code = readLines("week1/1w1_4.R")}

```

## Base R Visualizations
```{r, code = readLines("week1/1w1_5.R")}

```

## Practices
```{r}
# Problem 1 

# Create a data frame that includes two columns, one named "Animals" and the other named "Foods". The first column should be this vector (note the intentional repeated values): Dog, Cat, Fish, Fish, Lizard


#The second column should be this vector: Bread, Orange, Chocolate, Carrots, Milk


#### Write your code below:

Animals <- c("Dog", "Cat", "Fish", "Fish", "Lizard")
Foods <- c("Bread", "Orange", "Chocolate", "Carrots", "Milk")
df <- data.frame(Animals, Foods)
df
```

```{r}
# Problem 2

# Using the data frame created in Problem 2, use the table() command to create a frequency table for the column called "Animals".

#### Write your code below:

table(df$Animals)
```

```{r}
# Problem 3

# Use read.csv() to import the survey data included in this assignment. Using that data, make a histogram of the column called "pid7".


#### Write your code below:

df2 <- read.csv("week1/cces_sample_coursera.csv")
```

```{r}
hist(df2$pid7)
```

# Week 1 Synchronous
```{r child="week1/REUtidydata/tidydata.md"}

```

